name: Release on Folder Update

on:
  push:
    paths:
      - 'mod/compat2/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FOLDER_PATH: mod/compat2
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Zip the folder
      run: zip -r ${FOLDER_PATH}.zip ${FOLDER_PATH}/
      shell: bash

    - name: Fetch all tags
      run: git fetch --tags

    - name: Get the highest current version
      id: versioning
      run: |
        HIGHEST_TAG=$(git tag --list "${FOLDER_PATH}-v*" --sort=-v:refname | head -n 1 | sed "s|${FOLDER_PATH}-v||")
        if [[ -z "$HIGHEST_TAG" ]]; then
          HIGHEST_TAG=0
        fi
        echo "Highest existing tag version: $HIGHEST_TAG"
        echo "::set-output name=version::$HIGHEST_TAG"

    - name: Increment version and create tag
      id: new_version
      run: |
        VERSION=$(( ${HIGHEST_TAG} + 1 ))
        echo "New version: $VERSION"
        echo "::set-output name=version::$VERSION"
        NEW_TAG="${FOLDER_PATH}-v${VERSION}"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Delete previous tag if exists (locally and remotely)
      run: |
        if git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
          echo "Deleting existing tag: $NEW_TAG"
          git tag -d $NEW_TAG
          git push --delete origin $NEW_TAG
        else
          echo "No existing tag to delete."
        fi
      env:
        NEW_TAG: ${{ env.NEW_TAG }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        draft: false
        prerelease: false
        body: |
          Changes in this Release:
          - ${{ github.event.head_commit.message }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.FOLDER_PATH }}.zip
        asset_name: ${{ env.FOLDER_PATH }}-v${{ steps.new_version.outputs.version }}.zip
        asset_content_type: application/zip