
name: Zip archives

on:
  push:
    tags:
    - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Zip Files
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'main.zip'
        path: 'mod/main'
    - name: Create Git Release
      uses: docker://antonyurchenko/git-release:v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      env:
        CHANGELOG_FILE: none
      with:
        args: mod/main*.zip
