
name: Zip archives

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vimtor/action-zip@v1.2
        with:
          files: mod/main
          dest: main.zip

