# This is a basic workflow to help you get started with Actions

name: Zip archives

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      #- uses: ncipollo/release-action@v1.14.0

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'main.zip'
          path: 'mod/main'
          
      - name: Upload Release
        uses: ncipollo/release-action@v1.14.0
        with:
            artifacts: "main.zip"
            token: ${{ secrets.GITHUB_TOKEN }}    
            generateReleaseNotes: 'True'
            tag: 'Release'
