
name: Zip archives

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Archive Release
              uses: thedoctor0/zip-release@0.7.5
              with:
                type: 'zip'
                filename: 'main.zip'
                path: 'mod/main'

