name: Release on Folder Update

on:
  push:
    paths:
      - 'mod/compat2/**' # Hardcoded path for the workflow trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FOLDER_PATH: mod/compat2 # Define your folder path here as an environment variable
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      STATIC_TAG_NAME: release-mod-compat2 # Static tag name without version
    steps:
    - uses: actions/checkout@v2

    - name: Zip the folder
      run: |
        zip -r ${FOLDER_PATH}.zip ${FOLDER_PATH}/
      shell: bash

    - name: Create or Update Tag
      run: |
        if git rev-parse "$STATIC_TAG_NAME" >/dev/null 2>&1; then
          git tag -d $STATIC_TAG_NAME
          git push --delete origin $STATIC_TAG_NAME
        fi
        git tag $STATIC_TAG_NAME
        git push origin $STATIC_TAG_NAME
      env:
        STATIC_TAG_NAME: ${{ env.STATIC_TAG_NAME }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.STATIC_TAG_NAME }}
        release_name: Release ${{ env.STATIC_TAG_NAME }}
        draft: false
        prerelease: false
        body: |
          Changes in this Release:
          - ${{ github.event.head_commit.message }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.FOLDER_PATH }}.zip
        asset_name: ${{ env.FOLDER_PATH }}.zip
        asset_content_type: application/zip